// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCVUc5ZqADPXZpe3zOMeUm_v88_VXmbcQ',
    appId: '1:541548131487:web:b0d50c08a5b6d3e5461eaa',
    messagingSenderId: '541548131487',
    projectId: 'hackmit-2022',
    authDomain: 'hackmit-2022.firebaseapp.com',
    storageBucket: 'hackmit-2022.appspot.com',
    measurementId: 'G-53CMG29GYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0ND5xAcuzMhXDWsQQp7-qh90BZB2iwZQ',
    appId: '1:541548131487:android:ee26c8845560f1ce461eaa',
    messagingSenderId: '541548131487',
    projectId: 'hackmit-2022',
    storageBucket: 'hackmit-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNUo4mhdOWbsj7EFwradsM3544z3Dg2U',
    appId: '1:541548131487:ios:979d09f0e33fd67d461eaa',
    messagingSenderId: '541548131487',
    projectId: 'hackmit-2022',
    storageBucket: 'hackmit-2022.appspot.com',
    iosClientId: '541548131487-njdctin5spbovuoetquibtd3qp75j96l.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATNUo4mhdOWbsj7EFwradsM3544z3Dg2U',
    appId: '1:541548131487:ios:979d09f0e33fd67d461eaa',
    messagingSenderId: '541548131487',
    projectId: 'hackmit-2022',
    storageBucket: 'hackmit-2022.appspot.com',
    iosClientId: '541548131487-njdctin5spbovuoetquibtd3qp75j96l.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
